[package]
name = "magic-mirror"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dlib-face-recognition = "0.2.2"
dlib-face-recognition-sys = "19.22.0-rc.1"
half = "1.8"
nannou = { version = "0.18", features = ["spirv"] }
opencv = "0.63"
regex = "1"
ringbuf = "0.2"
shaderc = "0.7"
